export * as authApi from './auth'
export * as sessionApi from './auth/session'
export * as dashboardApi from './dashboard'
export * as auditApi from './sys/audit.ts'
export * as bannerApi from './sys/banner.ts'
export * as codegenApi from './sys/codegen.ts'
export * as configApi from './sys/config.ts'
export * as dictApi from './sys/dict.ts'
export * as fileApi from './sys/file.ts'
export * as accountApi from './iam/account'
export * as clientModuleApi from './iam/client_module'
export * as clientResourceApi from './iam/client_resource'
export * as deptApi from './iam/dept'
export * as groupApi from './iam/group'
export * as positionApi from './iam/position'
export * as resourceApi from './iam/resource'
export * as resourceModuleApi from './iam/resource_module'
export * as roleApi from './iam/role'
export * as messageApi from './message'
// 由 HEI 代码生成器生成。 Author: Charlie. 生成时间：2026-07-19 09:36:52.
export * as cgTestActivityApi from './biz/cg-test-activity'
// 由 HEI 代码生成器生成。 Author: Charlie. 生成时间：2026-07-19 09:40:19.
export * as cgTestCatalogApi from './biz/cg-test-catalog'
// 由 HEI 代码生成器生成。 Author: Charlie. 生成时间：2026-07-19 09:43:33.
export * as cgTestOrderApi from './biz/cg-test-order'
// 由 HEI 代码生成器生成。 Author: Charlie. 生成时间：2026-07-19 09:49:09.
export * as cgTestKnowledgeCategoryApi from './biz/cg-test-knowledge-category'

export * as msgNoticeApi from './message/notice'
export * as msgFeedbackApi from './message/feedback'
export * as weakPasswordApi from './sys/weakPassword'
