package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type routeOverride struct {
	Summary    string            `yaml:"summary"`
	Security   *bool             `yaml:"security"`
	Accept     string            `yaml:"accept"`
	BodyType   string            `yaml:"body_type"`
	QueryType  string            `yaml:"query_type"`
	Success    string            `yaml:"success"`
	Params     []overrideParam   `yaml:"params"`
	ExtraLines []string          `yaml:"extra_lines"`
}

type overrideParam struct {
	Name     string `yaml:"name"`
	In       string `yaml:"in"`
	Type     string `yaml:"type"`
	Required bool   `yaml:"required"`
	Desc     string `yaml:"desc"`
}

type overridesFile struct {
	Routes map[string]routeOverride `yaml:"routes"`
}

func loadOverrides(root string) overridesFile {
	path := filepath.Join(root, "scripts", "gen-swag", "overrides.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return overridesFile{Routes: map[string]routeOverride{}}
	}
	var f overridesFile
	if err := yaml.Unmarshal(data, &f); err != nil {
		fmt.Fprintf(os.Stderr, "warn: parse overrides.yaml: %v\n", err)
		return overridesFile{Routes: map[string]routeOverride{}}
	}
	if f.Routes == nil {
		f.Routes = map[string]routeOverride{}
	}
	return f
}

type annotator struct {
	root          string
	routes        []route
	routeIndex    map[string]routeLink
	handlerIdx    map[string]handlerInfo
	structIdx     map[string]structIndex
	resultIdx     map[string][]string
	pkgImportMap  map[string]string
	overrides     overridesFile
}

func newAnnotator(root string, routes []route) *annotator {
	routeIndex := buildRouteIndex(root)
	return &annotator{
		root:         root,
		routes:       routes,
		routeIndex:   routeIndex,
		handlerIdx:   buildHandlerIndex(root),
		structIdx:    buildStructIndex(root),
		resultIdx:    buildResultIndex(root),
		pkgImportMap: buildPkgImportMap(root, routeIndex),
		overrides:    loadOverrides(root),
	}
}

func (a *annotator) writeStubs(path string) error {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/gen-swag; DO NOT EDIT.\n\n")
	b.WriteString("package app\n\n")
	imports := map[string]bool{"hei-gin/internal/framework/core/response": true}
	for i, rt := range a.routes {
		lines, pkgs := a.annotate(rt)
		for p := range pkgs {
			if imp := a.pkgImportMap[p]; imp != "" {
				imports[imp] = true
			}
		}
		fmt.Fprintf(&b, "// swaggerRoute%d godoc\n", i)
		for _, line := range lines {
			fmt.Fprintf(&b, "// %s\n", line)
		}
		fmt.Fprintf(&b, "func swaggerRoute%d() {}\n\n", i)
	}
	formatted, err := formatGo(b.String())
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	return writeSwaggerImports(filepath.Join(filepath.Dir(path), "swagger_imports_gen.go"), imports)
}

func (a *annotator) annotate(rt route) ([]string, map[string]bool) {
	key := rt.Method + " " + rt.Path
	ov, hasOv := a.overrides.Routes[key]
	usedPkgs := map[string]bool{"response": true}

	link, hasLink := a.routeIndex[key]
	pkgName := link.PkgName
	modDir := link.ModDir
	handler := link.Handler
	summary := link.Summary

	if hasOv && ov.Summary != "" {
		summary = ov.Summary
	}
	if summary == "" {
		summary = fmt.Sprintf("%s %s", rt.Method, strings.TrimPrefix(rt.Path, "/"))
	}

	var hi handlerInfo
	if hasLink && handler != "" {
		hi = a.handlerIdx[handlerKey(modDir, handler)]
	}

	bindType, bindLoc := hi.BindType, hi.BindLoc
	if bindType == "" && handler != "" {
		bindType, bindLoc = inferBindFromHandler(handler)
	}
	if bindType == "" {
		bt, bl := inferFromPathSuffix(rt.Path, rt.Method)
		bindType, bindLoc = bt, bl
	}
	if hasOv && ov.BodyType != "" {
		bindType, bindLoc = a.qualifyType(ov.BodyType, pkgName, rt.Path), "body"
	}
	if hasOv && ov.QueryType != "" {
		bindType, bindLoc = a.qualifyType(ov.QueryType, pkgName, rt.Path), "query"
	}

	if bindType != "" && !strings.Contains(bindType, ".") {
		bindType = a.qualifyType(bindType, pkgName, rt.Path)
	}
	if bindType != "" {
		collectPkgFromType(bindType, usedPkgs)
	}

	tag := swaggerTag(rt.Path)
	routerPath := paramColonToBrace(rt.Path)

	var lines []string
	lines = append(lines, fmt.Sprintf("@Summary      %s", summary))
	lines = append(lines, fmt.Sprintf("@Tags         %s", tag))

	accept := "json"
	if bindLoc == "multipart" || (hasOv && ov.Accept == "multipart/form-data") {
		accept = "multipart/form-data"
	} else if hasOv && ov.Accept != "" {
		accept = ov.Accept
	}
	lines = append(lines, fmt.Sprintf("@Accept       %s", accept))
	lines = append(lines, "@Produce      json")

	if hasOv && len(ov.Params) > 0 {
		for _, p := range ov.Params {
			req := "false"
			if p.Required {
				req = "true"
			}
			lines = append(lines, fmt.Sprintf("@Param        %s %s %s %s \"%s\"", p.Name, p.In, p.Type, req, p.Desc))
		}
	} else {
		for _, p := range pathParams(rt.Path) {
			lines = append(lines, fmt.Sprintf("@Param        %s path string true \"%s\"", p, p))
		}
		if bindLoc == "multipart" {
			lines = append(lines, `@Param        file formData file true "上传文件"`)
			lines = append(lines, `@Param        storage_provider formData string false "存储提供方"`)
		} else if bindLoc == "body" && bindType != "" {
			lines = append(lines, fmt.Sprintf(`@Param        body body %s true "请求体"`, bindType))
		} else if bindLoc == "query" && bindType != "" {
			lines = append(lines, expandQueryParams(bindType, a.lookupFields(bindType, modDir, pkgName))...)
		} else if bindType != "" && bindLoc == "" && rt.Method == "POST" {
			lines = append(lines, fmt.Sprintf(`@Param        body body %s true "请求体"`, bindType))
		} else if bindType != "" && bindLoc == "" && rt.Method == "GET" {
			lines = append(lines, expandQueryParams(bindType, a.lookupFields(bindType, modDir, pkgName))...)
		}
	}

	if hasOv {
		for _, extra := range ov.ExtraLines {
			lines = append(lines, extra)
		}
	}

	success := a.successType(rt, hi, link, hasLink)
	if hasOv && ov.Success != "" {
		success = ov.Success
	}
	collectPkgFromType(success, usedPkgs)
	lines = append(lines, fmt.Sprintf("@Success      200 {object} %s", success))
	lines = append(lines, "@Failure      400 {object} response.SwaggerApiResponse")
	if needsAuth(rt.Path, hasOv, ov) {
		lines = append(lines, "@Failure      401 {object} response.SwaggerApiResponse")
		lines = append(lines, "@Failure      403 {object} response.SwaggerApiResponse")
		lines = append(lines, "@Security     BearerAuth")
	}
	lines = append(lines, "@Failure      404 {object} response.SwaggerApiResponse")
	lines = append(lines, "@Failure      500 {object} response.SwaggerApiResponse")
	lines = append(lines, fmt.Sprintf("@Router       %s [%s]", routerPath, strings.ToLower(rt.Method)))
	return lines, usedPkgs
}

func (a *annotator) lookupFields(bindType, modDir, pkgName string) []fieldMeta {
	if strings.HasPrefix(bindType, "schema.") {
		if idx, ok := a.structIdx["schema"]; ok {
			return idx[strings.TrimPrefix(bindType, "schema.")]
		}
		return nil
	}
	if idx, ok := a.structIdx[modDir]; ok {
		short := bindType
		if i := strings.LastIndex(bindType, "."); i >= 0 {
			short = bindType[i+1:]
		}
		return idx[short]
	}
	return nil
}

func (a *annotator) successType(rt route, hi handlerInfo, link routeLink, hasLink bool) string {
	handler := link.Handler
	pkg := link.PkgName
	types := a.resultIdx[link.ModDir]

	// 写操作：data 为 null
	if isMutationRoute(rt, handler, hi) {
		return "response.SwaggerApiVoidResponse"
	}

	// 分页：展开 records 元素类型
	if hi.IsPage || isPagePath(rt.Path) || isPageHandler(handler) {
		recordType := inferPageRecordType(handler, pkg, types)
		if recordType != "" && pkg != "" {
			return fmt.Sprintf("response.SwaggerApiPageResponse{data=response.SwaggerPageData{records=[]%s.%s}}", pkg, recordType)
		}
		return "response.SwaggerApiPageResponse"
	}

	// 树形列表
	if handler == "tree" || handler == "portalTree" {
		if recordType := inferResultType(handler, types, pkg); recordType != "" && pkg != "" {
			return fmt.Sprintf("response.SwaggerApiResponse{data=[]%s.%s}", pkg, recordType)
		}
	}

	// 详情 / 查询类
	resultShort := ""
	if hasLink && handler != "" {
		resultShort = inferResultType(handler, types, pkg)
	}
	if resultShort == "" {
		return "response.SwaggerApiResponse"
	}
	if pkg == "" {
		return "response.SwaggerApiResponse"
	}
	return fmt.Sprintf("response.SwaggerApiResponse{data=%s.%s}", pkg, resultShort)
}

func isPagePath(path string) bool {
	lower := strings.ToLower(path)
	return strings.HasSuffix(lower, "/page") || strings.HasSuffix(lower, "/my-page") ||
		strings.HasSuffix(lower, "/review-page") || strings.HasSuffix(lower, "/identity/page")
}

func isMutationRoute(rt route, handler string, hi handlerInfo) bool {
	if hi.ResultType == "_non_nil" {
		return false
	}
	lower := strings.ToLower(rt.Path)
	if strings.Contains(lower, "/upload") {
		return false
	}
	return strings.HasSuffix(lower, "/create") || strings.HasSuffix(lower, "/update") ||
		strings.HasSuffix(lower, "/delete") || strings.Contains(lower, "/grant-") ||
		strings.HasSuffix(lower, "/approve") || strings.HasSuffix(lower, "/reject") ||
		strings.HasSuffix(lower, "/revoke") || strings.HasSuffix(lower, "/logout") ||
		strings.HasSuffix(lower, "/cancel") || strings.HasSuffix(lower, "/exchange")
}

func expandQueryParams(bindType string, fields []fieldMeta) []string {
	if len(fields) == 0 {
		// fallback single body reference for unknown structs
		if bindType == "schema.IDQuery" {
			return []string{`@Param        id query string true "ID"`}
		}
		if bindType == "schema.PageQuery" {
			return []string{
				`@Param        current query int false "页码"`,
				`@Param        size query int false "每页条数"`,
			}
		}
		return nil
	}
	var lines []string
	for _, f := range fields {
		req := "false"
		if f.Required {
			req = "true"
		}
		name := f.FormName
		if name == "" || name == "-" {
			continue
		}
		lines = append(lines, fmt.Sprintf(`@Param        %s query %s %s "%s"`, name, f.Swagger, req, name))
	}
	return lines
}

func pathParams(path string) []string {
	var out []string
	for i := 0; i < len(path); i++ {
		if path[i] == ':' {
			j := i + 1
			for j < len(path) && path[j] != '/' {
				j++
			}
			out = append(out, path[i+1:j])
			i = j - 1
		}
	}
	return out
}

func needsAuth(path string, hasOv bool, ov routeOverride) bool {
	if hasOv && ov.Security != nil {
		return *ov.Security
	}
	if strings.Contains(path, "/public/") || strings.HasSuffix(path, "/captcha") ||
		strings.HasSuffix(path, "/password-key") || strings.HasSuffix(path, "/login") ||
		strings.HasSuffix(path, "/register") || strings.HasSuffix(path, "/site-footer") ||
		strings.HasSuffix(path, "/auth-options") {
		return false
	}
	if strings.Contains(path, "/forgot-password") || strings.Contains(path, "/reset-password") ||
		strings.Contains(path, "/send-login-code") || strings.Contains(path, "/register/send-code") {
		return false
	}
	if strings.Contains(path, "/oauth/") && (strings.Contains(path, "/authorize") || strings.Contains(path, "/callback")) {
		return false
	}
	return strings.Contains(path, "/v1/admin/") || strings.Contains(path, "/v1/portal/")
}

func formatGo(src string) ([]byte, error) {
	return formatSource([]byte(src))
}

func (a *annotator) qualifyType(typ, pkgName, path string) string {
	if strings.Contains(typ, ".") {
		return typ
	}
	if pkgName != "" {
		return pkgName + "." + typ
	}
	if pkg := inferPkgFromPath(path, a.pkgImportMap); pkg != "" {
		return pkg + "." + typ
	}
	if isAuthPath(path) {
		return "auth." + typ
	}
	return typ
}

func inferPkgFromPath(path string, pkgMap map[string]string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	for i, p := range parts {
		switch p {
		case "profile":
			return "profile"
		case "workspace":
			return "workspace"
		case "biz":
			if i+1 < len(parts) {
				seg := strings.ReplaceAll(parts[i+1], "-", "_")
				if _, ok := pkgMap[seg]; ok {
					return seg
				}
			}
		case "sys", "iam":
			if i+1 < len(parts) {
				seg := pluralToSingular(parts[i+1])
				if _, ok := pkgMap[seg]; ok {
					return seg
				}
			}
		}
	}
	return ""
}

func pluralToSingular(seg string) string {
	seg = strings.ReplaceAll(seg, "-", "_")
	m := map[string]string{
		"accounts": "account", "roles": "role", "groups": "group", "depts": "dept",
		"positions": "position", "clients": "client", "resources": "resource",
		"dicts": "dict", "notices": "notice", "files": "file", "configs": "config",
		"banners": "banner", "audits": "audit", "jobs": "job", "feedbacks": "feedback",
		"weak_passwords": "weak_password",
	}
	if s, ok := m[seg]; ok {
		return s
	}
	if strings.HasSuffix(seg, "s") && len(seg) > 1 {
		return seg[:len(seg)-1]
	}
	return seg
}

func isAuthPath(path string) bool {
	return strings.Contains(path, "/login") ||
		strings.Contains(path, "/register") ||
		strings.Contains(path, "/captcha") ||
		strings.Contains(path, "/password-key") ||
		strings.Contains(path, "/forgot-password") ||
		strings.Contains(path, "/reset-password") ||
		strings.Contains(path, "/send-login-code") ||
		strings.Contains(path, "/auth/refresh") ||
		strings.Contains(path, "/logout") ||
		strings.Contains(path, "/cancel")
}

func collectPkgFromType(typ string, out map[string]bool) {
	typ = strings.TrimPrefix(typ, "{object} ")
	if i := strings.Index(typ, "{"); i >= 0 {
		inner := typ[i+1:]
		if j := strings.Index(inner, "="); j >= 0 {
			collectPkgFromType(inner[j+1:], out)
		}
		typ = typ[:i]
	}
	if i := strings.Index(typ, "."); i >= 0 {
		out[typ[:i]] = true
	}
}

func buildPkgImportMap(root string, routeIndex map[string]routeLink) map[string]string {
	m := map[string]string{
		"response": "hei-gin/internal/framework/core/response",
		"schema":   "hei-gin/internal/framework/core/schema",
		"auth":     "hei-gin/internal/modules/auth",
		"oauth":     "hei-gin/internal/modules/auth/oauth",
	}
	for _, link := range routeIndex {
		if link.PkgName == "" || link.ModDir == "" {
			continue
		}
		rel, err := filepath.Rel(root, link.ModDir)
		if err != nil {
			continue
		}
		m[link.PkgName] = "hei-gin/" + filepath.ToSlash(rel)
	}
	_ = filepath.Walk(filepath.Join(root, "internal"), func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Base(path) != "param.go" {
			return nil
		}
		pkg := packageNameFromFile(path)
		if pkg == "" {
			return nil
		}
		rel, err := filepath.Rel(root, filepath.Dir(path))
		if err != nil {
			return nil
		}
		m[pkg] = "hei-gin/" + filepath.ToSlash(rel)
		return nil
	})
	return m
}

func writeSwaggerImports(path string, imports map[string]bool) error {
	if len(imports) == 0 {
		return nil
	}
	list := make([]string, 0, len(imports))
	for imp := range imports {
		list = append(list, imp)
	}
	sort.Strings(list)
	var b strings.Builder
	b.WriteString("// Code generated by scripts/gen-swag; DO NOT EDIT.\n\n")
	b.WriteString("package app\n\nimport (\n")
	for _, imp := range list {
		fmt.Fprintf(&b, "\t_ %q\n", imp)
	}
	b.WriteString(")\n")
	formatted, err := formatGo(b.String())
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
