// Code generated by mapstruct. DO NOT EDIT.
// versions:
//   mapstruct v1.0.0

package user

import "hei-gin/sdk/utils"

// SysUserToUserVO 将 user.SysUser 映射到 user.UserVO
func SysUserToUserVO(src *SysUser) *UserVO {
	if src == nil {
		return nil
	}

	dst := &UserVO{}

	dst.ID = src.ID
	dst.Username = src.Username
	dst.Password = src.Password
	dst.Nickname = src.Nickname
	dst.Avatar = src.Avatar
	dst.Motto = src.Motto
	dst.Gender = src.Gender
	dst.Email = src.Email
	dst.Github = src.Github
	dst.Phone = src.Phone
	dst.OrgID = src.OrgID
	dst.PositionID = src.PositionID
	dst.GroupID = src.GroupID
	dst.Status = src.Status
	dst.LastLoginIP = src.LastLoginIP
	dst.LoginCount = src.LoginCount
	dst.CreatedBy = src.CreatedBy
	dst.UpdatedBy = src.UpdatedBy

	// *time.Time → string manual conversion
	dst.Birthday = utils.FormatDateTimePtr(src.Birthday)
	dst.LastLoginAt = utils.FormatDateTimePtr(src.LastLoginAt)
	dst.CreatedAt = utils.FormatDateTimePtr(src.CreatedAt)
	dst.UpdatedAt = utils.FormatDateTimePtr(src.UpdatedAt)

	return dst
}

// UserVOToSysUser 将 user.UserVO 映射到 user.SysUser
func UserVOToSysUser(src *UserVO) *SysUser {
	if src == nil {
		return nil
	}

	dst := &SysUser{}

	dst.ID = src.ID
	dst.Username = src.Username
	dst.Nickname = src.Nickname
	dst.Avatar = src.Avatar
	dst.Motto = src.Motto
	dst.Gender = src.Gender
	dst.Email = src.Email
	dst.Github = src.Github
	dst.Phone = src.Phone
	dst.OrgID = src.OrgID
	dst.PositionID = src.PositionID
	dst.GroupID = src.GroupID
	dst.Status = src.Status
	dst.LastLoginIP = src.LastLoginIP
	dst.LoginCount = src.LoginCount
	dst.CreatedBy = src.CreatedBy
	dst.UpdatedBy = src.UpdatedBy
	dst.Password = src.Password

	// string → *time.Time manual conversion
	dst.Birthday = utils.ParseDateTimePtr(&src.Birthday)
	dst.LastLoginAt = utils.ParseDateTimePtr(&src.LastLoginAt)
	dst.CreatedAt = utils.ParseDateTimePtr(&src.CreatedAt)
	dst.UpdatedAt = utils.ParseDateTimePtr(&src.UpdatedAt)

	return dst
}
