// Code generated by scripts/gen-swag; DO NOT EDIT.

package app

import (
	_ "hei-gin/internal/framework/core/response"
	_ "hei-gin/internal/framework/core/schema"
	_ "hei-gin/internal/modules/auth"
	_ "hei-gin/internal/modules/biz/cg_test_activity"
	_ "hei-gin/internal/modules/biz/cg_test_catalog"
	_ "hei-gin/internal/modules/biz/cg_test_knowledge_category"
	_ "hei-gin/internal/modules/biz/cg_test_order"
	_ "hei-gin/internal/modules/iam/account"
	_ "hei-gin/internal/modules/iam/client"
	_ "hei-gin/internal/modules/iam/dept"
	_ "hei-gin/internal/modules/iam/group"
	_ "hei-gin/internal/modules/iam/position"
	_ "hei-gin/internal/modules/iam/resource"
	_ "hei-gin/internal/modules/iam/role"
	_ "hei-gin/internal/modules/profile"
	_ "hei-gin/internal/modules/profile/identity"
	_ "hei-gin/internal/modules/sys/audit"
	_ "hei-gin/internal/modules/sys/banner"
	_ "hei-gin/internal/modules/sys/codegen"
	_ "hei-gin/internal/modules/sys/config"
	_ "hei-gin/internal/modules/sys/dict"
	_ "hei-gin/internal/modules/sys/feedback"
	_ "hei-gin/internal/modules/sys/file"
	_ "hei-gin/internal/modules/sys/job"
	_ "hei-gin/internal/modules/sys/notice"
	_ "hei-gin/internal/modules/sys/weak_password"
)
